services:
  - type: web
    name: stock-signal-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: https://financialmodelingprep.com/api/v3/profile/AAPL?apikey=3cNanCgIW7CR4hL5zpQqTo2jc9cPvy0k
        sync: false
